version: '3.9'

services:
  app:
    image: app:latest
    container_name: app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod   # ou dev, teste, etc.
    restart: unless-stopped
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Arquivo principal de configuração do nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Configurações adicionais de sites (server blocks)
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      # Arquivos HTML estáticos
      - ./nginx/html:/usr/share/nginx/html:ro
    depends_on:
      - app