version: '3.9'

services:
  spring-app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod   # ou dev, teste, etc.
    restart: unless-stopped
