spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/investment_db
    driver-class-name: org.postgresql.Driver
    username: backendUser
    password: b@ckendP@ssw0rd
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      pool-name: HikariCP-prod
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        show_sql: false
    hibernate:
      ddl-auto: update
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
